### ISSUE TITLE
All my links (<a href=""></a> ) are moving far away when I hover over them

### ISSUE THREAD

**Issue by Maximilian16061996** [Maximilian16061996/Issues-File#1]
Hey guys, 

I have been starting to try my own HTML and CSS project and set up a basic website with a login form and some general links. The links are not connected to go anywhere yet but will be used for later. However, I noticed that somehow when I hover over them that the link-texts shoot to weird spots on the webpage and I cannot click them. Once I change the link in the log in section, all the others are somehow affected I suppose. If I delete that link "Forgot Password", all the others work again. 
Do you have an idea why this happens? I used CSS chaining to only target specific links in my code, but it doesn't work at all. 

Any ideas? I am really lost.

This is the link to my Github file: 

https://github.com/Maximilian16061996/Issues-File

Looking forward to hearing from you!

Best Regards Maximilian

**Comment by sophianyberg** [comment]
Hi, I think this was solved at [https://discuss.codecademy.com/t/all-my-links-a-href-a-are-moving-far-away-when-i-hover-over-them/574515](https://discuss.codecademy.com/t/all-my-links-a-href-a-are-moving-far-away-when-i-hover-over-them/574515). Could you close it?

**Comment by sophianyberg** [comment]
Thank you!
